### ISSUE TITLE
Compilation failed while executing : ld64

### ISSUE THREAD

**Issue by fmrunware** [distriqt/ANE-Core#4]
When compiling with Camera ANE + Core ANE + Local Notification ANE, it fails with this message : 

Une erreur s’est produite lors du groupement de l’application :
.

Undefined symbols for architecture arm64:
  "_DTCoreDidFinishLaunchingWithOptionsNotification", referenced from:
      _DTCoreDidFinishLaunchingWithOptions in libcom.distriqt.Core.a(Core.o)
  "_DTCoreDidReceiveLocalNotificationNotification", referenced from:
      _DTCoreDidReceiveLocalNotification in libcom.distriqt.Core.a(Core.o)
Undefined symbols for architecture armv7:
  "_DTCoreDidRegisterForRemoteNotificationsWithDeviceTokenNotification", referenced from:
      _DTCoreDidRegisterForRemoteNotificationsWithDeviceToken in libcom.distriqt.Core.a(Core.o)
  "_DTCoreDidFailToRegisterForRemoteNotificationsWithErrorNotification", referenced from:
      _DTCoreDidFailToRegisterForRemoteNotificationsWithError in libcom.distriqt.Core.a(Core.o)
  "_DTCoreOpenURLNotification", referenced from:
      _DTCoreOpenURL in libcom.distriqt.Core.a(Core.o)
  "_DTCoreDidRegisterForRemoteNotificationsWithDeviceTokenNotification", referenced from:
      _DTCoreDidRegisterForRemoteNotificationsWithDeviceToken in libcom.distriqt.Core.a(Core.o)
  "_DTCoreDidReceiveRemoteNotificationNotification", referenced from:
      _DTCoreDidReceiveRemoteNotification in libcom.distriqt.Core.a(Core.o)
  "_DTCoreDidReceiveRemoteNotificationNotification", referenced from:
      _DTCoreDidReceiveRemoteNotification in libcom.distriqt.Core.a(Core.o)
  "_DTCoreOpenURLNotification", referenced from:
      _DTCoreOpenURL in libcom.distriqt.Core.a(Core.o)
  "_DTCoreDidFailToRegisterForRemoteNotificationsWithErrorNotification", referenced from:
      _DTCoreDidFailToRegisterForRemoteNotificationsWithError in libcom.distriqt.Core.a(Core.o)
  "_DTCoreDidReceiveLocalNotificationNotification", referenced from:
      _DTCoreDidReceiveLocalNotification in libcom.distriqt.Core.a(Core.o)
ld: symbol(s) not found for architecture arm64
  "_DTCoreDidFinishLaunchingWithOptionsNotification", referenced from:
      _DTCoreDidFinishLaunchingWithOptions in libcom.distriqt.Core.a(Core.o)
ld: symbol(s) not found for architecture armv7
Compilation failed while executing : ld64

I work with Flash Builder 4.7, Flex SDK 4.14.1 and AIR 17.

I just follow instructions and example code. Is it something more to do ?

Regards,

Fabrice

NB : It works fine on Android. I just give a try on IntelliJ and it give me the same error on iOS. Continue working on Android.

**Comment by marchbold** [comment]
Hi,
We've just updated a few of the ANE's you've listed against the latest Core library. Could you please update them all and let me know if you are still having this issue.

**Comment by fmrunware** [comment]
Perfect. It works like a charm on both platforms. Thank you.

**Comment by marchbold** [comment]
Thanks for letting us know.
