### ISSUE TITLE
Unable to output .ipa file using AIR SDK 33.1.1.476

### ISSUE THREAD

**Issue by crooksy88** [distriqt/ANE-Core#27]
Using AIR SDK 33.1.1.476 and the latest version of Core ANE 6.3.022.
Xcode Version 11.1 (11A1027)
MacOS 10.14.6

When I publish my app without any ANE's the .ipa file is output successfully.

When I add the Core.ANE I get this error from ADT and no file is output.

Would you have any idea what this issue is and how to fix this?

Thanks,

Mark

```
Undefined symbols for architecture armv7:
  "___darwin_check_fd_set_overflow", referenced from:
      __ZN26PlatformPrimitiveSocketTCP16HaveIncomingDataEv in libRuntimeHMAOT.arm-air.a(OSXPrimitiveSocket.o)
      __ZN14PlatformSelect12WaitForEventEjPb in libRuntimeHMAOT.arm-air.a(OSXPrimitiveSocket.o)
      __ZN20PlatformSecureSocket17WaitOnSocketErrorElNS_15WaitReadOrWriteEb in libRuntimeHMAOT.arm-air.a(CTSecureSocket.o)
      __ZN17MacDatagramSocket11ReceiveImplEPhPiR11FlashStringRiS3_S4_i in libRuntimeHMAOT.arm-air.a(OSXDatagramSocket.o)
      __ZN26PlatformPrimitiveSocketTCP16HaveIncomingDataEv in libRuntimeHMAOT.arm-air.a(OSXPrimitiveSocket.o)
      __ZN14PlatformSelect12WaitForEventEjPb in libRuntimeHMAOT.arm-air.a(OSXPrimitiveSocket.o)
      __ZN20PlatformSecureSocket17WaitOnSocketErrorElNS_15WaitReadOrWriteEb in libRuntimeHMAOT.arm-air.a(CTSecureSocket.o)
      __ZN17MacDatagramSocket11ReceiveImplEPhPiR11FlashStringRiS3_S4_i in libRuntimeHMAOT.arm-air.a(OSXDatagramSocket.o)
ld: symbol(s) not found for architecture armv7
Undefined symbols for architecture arm64:
  "___darwin_check_fd_set_overflow", referenced from:
      __ZN26PlatformPrimitiveSocketTCP16HaveIncomingDataEv in libRuntimeHMAOT.arm-air.a(OSXPrimitiveSocket.o)
      __ZN14PlatformSelect12WaitForEventEjPb in libRuntimeHMAOT.arm-air.a(OSXPrimitiveSocket.o)
      __ZN20PlatformSecureSocket17WaitOnSocketErrorEiNS_15WaitReadOrWriteEb in libRuntimeHMAOT.arm-air.a(CTSecureSocket.o)
      __ZN17MacDatagramSocket11ReceiveImplEPhPiR11FlashStringRiS3_S4_i in libRuntimeHMAOT.arm-air.a(OSXDatagramSocket.o)
ld: symbol(s) not found for architecture arm64
Compilation failed while executing : ld64
```

**Comment by SpikeApp** [comment]
If you need support on how to use Spike or solve a specific issue please join our support group at https://www.facebook.com/groups/spikeapp/

We do NOT give one on one support by e-mail.

Thank you!

The Spike Team

**Comment by crooksy88** [comment]
? 

What is spike and how does this relate to the Distriqt Core ANE?

**Comment by marchbold** [comment]
That SpikeApp account seems to have an automatic response and is not related to us. I will contact them about it.

**Comment by marchbold** [comment]
Can you tell me how you are packaging your application to replicate this error with the Core ANE, i.e. is this output from a command line build or through an IDE?

**Comment by crooksy88** [comment]
Hi Michael,

It's a command line build. 

I'm not sure if this is related but testing with a different app does build using AIR 33.1.1.259 using older distribution certs and provisioning profiles, but also fails using 33.1.1.476.

For this current app I'm updating I recently had to generate a new distribution cert and provisioning profile and this has forced to upgrade to 33.1.1.476. I believe it's something to do with the authority signing reference being different.

**Comment by marchbold** [comment]
Very odd, have you tried updating Xcode and the command line tools to the latest? Or is that the most recent release you can get on 10.14?

**Comment by marchbold** [comment]
Might be worth asking the Harman AIR team on the AIRSDK issue tracker. It seems to be related to the AIR sdk but not sure why the Core ANE is triggering it, could be additional linker options in the extension.
